[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts",
    "@gnosis.pm/safe-contracts/=lib/safe-contracts"
]

# Solidity compiler settings
[profile.solc]
optimizer = true
runs = 999999

# Fork settings (BSC mainnet)
[rpc_endpoints]
bsc = "${BSC_RPC_URL}"
bsc_testnet = "${BSC_RPC_URL}"

[etherscan]
bsc_testnet = { key = "RRYNWSXGPHNKIRYVUSAU5IJCIEDCB11GZM", url = "https://api-testnet.bscscan.com/api" }
